/* Administration des comptes CESAME (visible uniquement au Promoteur). */
const usersNav = document.querySelector('#usersNav');
const usersPage = document.querySelector('#users');
const showUsers = async () => {
  document.querySelectorAll('.page').forEach(page=>page.classList.toggle('active',page===usersPage));
  document.querySelectorAll('.nav-link').forEach(button=>button.classList.remove('active')); usersNav.classList.add('active');
  document.querySelector('#pageKicker').textContent='ADMINISTRATION';document.querySelector('#pageTitle').textContent='Utilisateurs';
  try { const result=await api('/api/users'); renderUsers(result.users); } catch(error) { toast(error.message); }
};
const renderUsers = users => { document.querySelector('#usersTable').innerHTML=users.map(user=>`<tr><td><strong>${user.name}</strong></td><td>${user.email}</td><td>${user.role}</td><td><span class="status ${user.active?'validée':'rejetée'}">${user.active?'Actif':'Désactivé'}</span></td><td class="right"><button class="action-mini" data-user-id="${user.id}" data-user-name="${encodeURIComponent(user.name)}" data-user-active="${user.active}">${user.active?'Gérer':'Réactiver'}</button></td></tr>`).join(''); };
usersNav.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();showUsers();},true);
const adminModal = (title, fields, handler) => { document.querySelector('#modalTitle').textContent=title;document.querySelector('#formFields').innerHTML=fields;document.querySelector('#operationForm').onsubmit=handler;document.querySelector('#modal').classList.remove('hidden'); };
document.querySelector('#createUser').addEventListener('click',()=>adminModal('Créer un compte',`<div class="form-grid"><label class="wide">Nom complet<input name="name" required /></label><label class="wide">Adresse e-mail<input name="email" type="email" required /></label><label>Rôle<select name="role"><option>Directeur</option><option>Scolarité</option><option>Promoteur</option></select></label><label>Mot de passe temporaire<input name="password" type="password" minlength="8" required /></label></div>`,async event=>{event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));try{await api('/api/users',{method:'POST',body:JSON.stringify(form)});document.querySelector('#modal').classList.add('hidden');toast('Compte créé avec succès.');showUsers();}catch(error){toast(error.message)}}));
document.addEventListener('click',event=>{const button=event.target.closest('[data-user-id]');if(!button)return;const id=button.dataset.userId;const name=decodeURIComponent(button.dataset.userName);const active=button.dataset.userActive==='true';adminModal(`Gérer ${name}`,`<div class="form-grid"><label class="wide">Nouveau mot de passe (facultatif)<input name="password" type="password" minlength="8" placeholder="Au moins 8 caractères" /></label><label class="wide">Statut<select name="active"><option value="true" ${active?'selected':''}>Actif</option><option value="false" ${!active?'selected':''}>Désactivé</option></select></label></div>`,async submit=>{submit.preventDefault();const form=Object.fromEntries(new FormData(submit.currentTarget));if(!form.password)delete form.password;form.active=form.active==='true';try{await api(`/api/users/${id}`,{method:'PATCH',body:JSON.stringify(form)});document.querySelector('#modal').classList.add('hidden');toast('Compte mis à jour.');showUsers();}catch(error){toast(error.message)}});});
const revealAdmin = () => { usersNav.classList.toggle('hidden',!data.user||data.user.role!=='Promoteur'); };
const originalRenderAll = renderAll; renderAll = function(){originalRenderAll();revealAdmin();};
