const STORAGE = 'cesame-finances-mvp-v1';
const today = new Date('2026-09-01');
const seed = {
  user: { name: 'Paul Mbarga', role: 'Promoteur' },
  incomes: [
    { id:'ENT-260901', label:'Versement formation — Nadège Atangana', category:'Frais de formation', date:'2026-09-01', mode:'MTN MoMo', amount:75000 },
    { id:'ENT-260829', label:'Inscription — Arnaud Mvondo', category:'Frais d’inscription', date:'2026-08-29', mode:'Espèces', amount:25000 },
    { id:'ENT-260827', label:'Versement formation — 12 étudiants', category:'Frais de formation', date:'2026-08-27', mode:'Virement', amount:410000 },
    { id:'ENT-260820', label:'Vente de supports pédagogiques', category:'Autres recettes', date:'2026-08-20', mode:'Espèces', amount:35000 }
  ],
  expenses: [
    { id:'SOR-260830', label:'Achat de fournitures', category:'Fournitures', date:'2026-08-30', amount:68500, status:'payée', validator:'D. Ndzié' },
    { id:'SOR-260828', label:'Connexion Internet — Août', category:'Télécommunications', date:'2026-08-28', amount:45000, status:'à valider', validator:'—' },
    { id:'SOR-260825', label:'Entretien groupe électrogène', category:'Maintenance', date:'2026-08-25', amount:95000, status:'payée', validator:'P. Mbarga' }
  ],
  planned: [
    { id:'PLN-1', label:'Rémunération formateurs', category:'Personnel', due:'2026-09-05', amount:450000, status:'prévue', note:'Paiement des prestations du mois d’août' },
    { id:'PLN-2', label:'Facture ENEO', category:'Charges courantes', due:'2026-09-04', amount:78000, status:'prévue', note:'Consommation électrique du centre' },
    { id:'PLN-3', label:'Loyer des locaux', category:'Loyer', due:'2026-08-31', amount:350000, status:'en retard', note:'Échéance mensuelle du bâtiment principal' },
    { id:'PLN-4', label:'Abonnement Internet', category:'Télécommunications', due:'2026-09-12', amount:45000, status:'prévue', note:'Fibre et téléphonie' }
  ],
  teachers: [
    { id:'FOR-1', name:'Mireille Ndzié', course:'Infographie', due:150000, paid:0, initials:'MN' },
    { id:'FOR-2', name:'Samuel Essomba', course:'Maintenance informatique', due:175000, paid:0, initials:'SE' },
    { id:'FOR-3', name:'Carine Mballa', course:'Bureautique', due:125000, paid:0, initials:'CM' }
  ],
  audit: [
    { text:'Paul Mbarga a validé la dépense « Achat de fournitures »', time:'Aujourd’hui à 10:42' },
    { text:'Scolarité a enregistré un versement de 75 000 FCFA', time:'Aujourd’hui à 09:18' },
    { text:'Directeur a planifié la facture ENEO', time:'Hier à 16:06' },
    { text:'Paul Mbarga a ajouté le formateur Samuel Essomba', time:'29 août 2026 à 11:28' }
  ]
};
let data = JSON.parse(localStorage.getItem(STORAGE)) || structuredClone(seed);
let currentType = 'income';
const can = () => Boolean(data.user && data.user.role);
const money = n => new Intl.NumberFormat('fr-FR').format(n || 0) + ' FCFA';
const save = () => localStorage.setItem(STORAGE, JSON.stringify(data));
const date = s => new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(s+'T12:00:00'));
const escape = s => String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
function addAudit(text){ data.audit.unshift({text, time:'À l’instant'}); save(); }
function toast(message){ const t=document.querySelector('#toast');t.textContent=message;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2800); }
function initials(name){return name.split(' ').map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function totals(){ return { income:data.incomes.reduce((a,x)=>a+x.amount,0), expense:data.expenses.filter(x=>x.status==='payée'||x.status==='validée').reduce((a,x)=>a+x.amount,0) } }
function renderAll(){
  const t=totals(), due=data.planned.filter(x=>x.status!=='payée'), upcoming=due.filter(x=>new Date(x.due+'T12')<=new Date('2026-09-08T12')).reduce((a,x)=>a+x.amount,0), overdue=due.filter(x=>x.status==='en retard').length;
  document.querySelector('#balance').textContent=money(t.income-t.expense); document.querySelector('#monthIncome').textContent=money(t.income);document.querySelector('#monthExpense').textContent=money(t.expense);document.querySelector('#upcomingTotal').textContent=money(upcoming);document.querySelector('#overdueText').textContent=overdue?`${overdue} dépense en retard`: 'Aucun retard';document.querySelector('#plannedBadge').textContent=due.length;
  document.querySelector('#sidebarName').textContent=data.user.name; document.querySelector('#sidebarRole').textContent=data.user.role;
  if(document.querySelector('#dashboard').classList.contains('active'))document.querySelector('#pageTitle').textContent=`Bonjour, ${data.user.name.split(' ')[0]} !`;
  renderDashboard(due);renderTables();renderPlanned();renderTeachers();renderReports();renderAudit();renderAccess();
}
function renderDashboard(due){
  const months=['Avr','Mai','Juin','Juil','Août','Sept']; const vals=[[37,23],[52,29],[41,35],[61,37],[75,44],[58,33]];
  document.querySelector('#chart').innerHTML=vals.map((v,i)=>`<div class="bar-set" data-month="${months[i]}"><i class="bar in" style="height:${v[0]}%"></i><i class="bar out" style="height:${v[1]}%"></i></div>`).join('');
  document.querySelector('#upcomingList').innerHTML=due.sort((a,b)=>a.due.localeCompare(b.due)).slice(0,4).map(x=>`<div class="compact-item"><div class="due-icon">◷</div><div><strong>${escape(x.label)}</strong><small>${x.status==='en retard'?'En retard depuis le ': 'Échéance : '}${date(x.due)}</small></div><span class="amount">${money(x.amount)}</span></div>`).join('') || '<p class="muted">Aucune échéance à venir.</p>';
  const ops=[...data.incomes.map(x=>({...x,type:'income',status:'reçu'})),...data.expenses.map(x=>({...x,type:'expense'}))].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,5);
  document.querySelector('#recentTable').innerHTML=ops.map(x=>`<tr><td>${escape(x.label)}</td><td>${escape(x.category)}</td><td>${date(x.date)}</td><td><span class="status ${x.status}">${x.status}</span></td><td class="right ${x.type==='income'?'amount-income':'amount-expense'}">${x.type==='income'?'+':'−'} ${money(x.amount)}</td></tr>`).join('');
  document.querySelector('#alertBanner').innerHTML=due.some(x=>x.status==='en retard')?`<strong>⚠ Attention :</strong> vous avez ${due.filter(x=>x.status==='en retard').length} dépense(s) en retard. <button data-go="planned">Les consulter</button>`:''; document.querySelector('#alertBanner').classList.toggle('hidden',!due.some(x=>x.status==='en retard'));
}
function renderTables(){
 const fill=(items,id,type)=>document.querySelector(id).innerHTML=items.sort((a,b)=>b.date.localeCompare(a.date)).map(x=>type==='income'?`<tr><td>${x.id}</td><td>${escape(x.label)}</td><td>${escape(x.category)}</td><td>${date(x.date)}</td><td>${x.mode||'—'}</td><td class="right amount-income">+ ${money(x.amount)}</td></tr>`:`<tr><td>${escape(x.label)}</td><td>${escape(x.category)}</td><td>${date(x.date)}</td><td><span class="status ${x.status}">${x.status}</span></td><td>${x.validator}</td><td class="right amount-expense">− ${money(x.amount)}</td><td>${x.status==='à valider'&&can('expense')?`<button class="action-mini" data-validate="${x.id}">Valider</button>`:''}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">Aucune opération.</td></tr>';
 fill(data.incomes,'#incomeTable','income');fill(data.expenses,'#expenseTable','expense');
 const cats=[...new Set(data.incomes.map(x=>x.category))];document.querySelector('#incomeFilter').innerHTML='<option value="all">Toutes les catégories</option>'+cats.map(x=>`<option>${x}</option>`).join('');
}
function renderPlanned(){document.querySelector('#plannedCards').innerHTML=data.planned.sort((a,b)=>a.due.localeCompare(b.due)).map(x=>`<article class="planned-card ${x.status==='en retard'?'overdue':''}"><span class="category">${escape(x.category).toUpperCase()}</span><h3>${escape(x.label)}</h3><p>${escape(x.note||'Aucune observation')}</p><footer><div><small>Échéance</small><br><strong>${date(x.due)}</strong></div><div class="right"><small>Montant</small><br><strong>${money(x.amount)}</strong></div></footer><div style="margin-top:14px;display:flex;justify-content:space-between;align-items:center"><span class="status ${x.status}">${x.status}</span>${x.status!=='payée'&&can('expense')?`<button class="action-mini" data-pay="${x.id}">Marquer payée</button>`:''}</div></article>`).join('')}
function renderTeachers(){const due=data.teachers.reduce((a,x)=>a+x.due,0), paid=data.teachers.reduce((a,x)=>a+x.paid,0);document.querySelector('#teacherDue').textContent=money(due);document.querySelector('#teacherCount').textContent=data.teachers.filter(x=>x.due>0).length;document.querySelector('#teacherPaid').textContent=money(paid);document.querySelector('#teacherCards').innerHTML=data.teachers.map(x=>`<article class="teacher-card"><div class="teacher-head"><div class="avatar">${x.initials||initials(x.name)}</div><div><strong>${escape(x.name)}</strong><small>${escape(x.course)}</small></div></div><div class="teacher-due">Montant à payer <strong>${money(x.due)}</strong></div><footer><span>Payé : ${money(x.paid)}</span>${x.due&&can('expense')?`<button class="action-mini" data-payteacher="${x.id}">Payer</button>`:'<span>À jour</span>'}</footer></article>`).join('')}
function renderReports(){const t=totals();document.querySelector('#reportSummary').innerHTML=`<div><span>Entrées enregistrées</span><strong class="amount-income">${money(t.income)}</strong></div><div><span>Sorties payées</span><strong class="amount-expense">${money(t.expense)}</strong></div><div><span>Résultat net</span><strong>${money(t.income-t.expense)}</strong></div><div><span>Engagements à venir</span><strong>${money(data.planned.filter(x=>x.status!=='payée').reduce((a,x)=>a+x.amount,0))}</strong></div>`;const groups={};data.expenses.forEach(x=>groups[x.category]=(groups[x.category]||0)+x.amount);const max=Math.max(...Object.values(groups),1);document.querySelector('#expenseBreakdown').innerHTML=Object.entries(groups).map(([k,v])=>`<div class="break-row"><span>${escape(k)}</span><div class="progress"><i style="width:${v/max*100}%"></i></div><strong>${money(v)}</strong></div>`).join('')||'<p class="muted">Pas encore de dépense.</p>'}
function renderAudit(){document.querySelector('#auditList').innerHTML=data.audit.map(x=>`<div class="audit-item">${escape(x.text)}<small>${x.time}</small></div>`).join('')}
function renderAccess(){document.querySelectorAll('.create').forEach(b=>{const type=b.dataset.type;b.classList.toggle('hidden',!can(type));});document.querySelector('#quickAdd').classList.toggle('hidden',!can('income'));}
function fields(type){const common=`<label class="wide">Libellé<input name="label" required placeholder="Ex. Versement formation" /></label><label>Montant (FCFA)<input name="amount" type="number" min="1" required /></label>`;if(type==='income')return `<div class="form-grid">${common}<label>Catégorie<select name="category"><option>Frais de formation</option><option>Frais d’inscription</option><option>Autres recettes</option></select></label><label>Date<input name="date" type="date" value="2026-09-01" required /></label><label>Mode de paiement<select name="mode"><option>Espèces</option><option>MTN MoMo</option><option>Orange Money</option><option>Virement</option></select></label></div>`;if(type==='expense')return `<div class="form-grid">${common}<label>Catégorie<select name="category"><option>Fournitures</option><option>Maintenance</option><option>Personnel</option><option>Charges courantes</option><option>Autre</option></select></label><label>Date<input name="date" type="date" value="2026-09-01" required /></label><label class="wide">Observation<input name="note" placeholder="Justificatif ou précision" /></label></div>`;if(type==='planned')return `<div class="form-grid">${common}<label>Catégorie<select name="category"><option>Personnel</option><option>Charges courantes</option><option>Loyer</option><option>Télécommunications</option><option>Autre</option></select></label><label>Échéance<input name="date" type="date" value="2026-09-05" required /></label><label class="wide">Observation<input name="note" placeholder="Détails de la dépense prévue" /></label></div>`;return `<div class="form-grid"><label class="wide">Nom complet<input name="name" required placeholder="Ex. Anne Ndzié" /></label><label class="wide">Formation / matière<input name="course" required placeholder="Ex. Infographie" /></label><label class="wide">Montant à payer (FCFA)<input name="amount" type="number" min="0" required /></label></div>`}
function openModal(type){if(!can(type)){toast('Votre rôle ne permet pas cette action.');return}currentType=type;const titles={income:'Enregistrer une entrée',expense:'Enregistrer une sortie',planned:'Planifier une dépense',teacher:'Ajouter un formateur'};document.querySelector('#modalTitle').textContent=titles[type];document.querySelector('#formFields').innerHTML=fields(type);document.querySelector('#modal').classList.remove('hidden')}
function submitOperation(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const amount=+f.amount;if(currentType==='income'){data.incomes.unshift({id:'ENT-'+Date.now().toString().slice(-6),label:f.label,category:f.category,date:f.date,mode:f.mode,amount});addAudit(`${data.user.name} a enregistré une entrée de ${money(amount)}`)}if(currentType==='expense'){data.expenses.unshift({id:'SOR-'+Date.now().toString().slice(-6),label:f.label,category:f.category,date:f.date,amount,status:'à valider',validator:'—'});addAudit(`${data.user.name} a soumis une dépense de ${money(amount)} à validation`)}if(currentType==='planned'){data.planned.unshift({id:'PLN-'+Date.now(),label:f.label,category:f.category,due:f.date,amount,status:'prévue',note:f.note});addAudit(`${data.user.name} a planifié la dépense « ${f.label} »`)}if(currentType==='teacher'){data.teachers.unshift({id:'FOR-'+Date.now(),name:f.name,course:f.course,due:amount,paid:0,initials:initials(f.name)});addAudit(`${data.user.name} a ajouté le formateur ${f.name}`)}save();document.querySelector('#modal').classList.add('hidden');renderAll();toast('Enregistrement effectué.');}
function setPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===id));document.querySelectorAll('.nav-link').forEach(x=>x.classList.toggle('active',x.dataset.page===id));const labels={dashboard:['VUE D’ENSEMBLE',`Bonjour, ${data.user.name.split(' ')[0]} 👋`],incomes:['ENCAISSEMENTS','Entrées'],expenses:['DÉCAISSEMENTS','Sorties'],planned:['PRÉVISIONNEL','Dépenses planifiées'],teachers:['ÉQUIPE PÉDAGOGIQUE','Formateurs'],'permanent-staff':['CONFIDENTIEL','Personnel permanent'],reports:['ANALYSE','Rapports financiers'],audit:['TRAÇABILITÉ','Historique & audit'],account:['SÉCURITÉ','Mon compte']};document.querySelector('#pageKicker').textContent=labels[id][0];document.querySelector('#pageTitle').textContent=labels[id][1];window.scrollTo(0,0)}
document.querySelector('#loginForm').addEventListener('submit',e=>{e.preventDefault();data.user.role=document.querySelector('#roleSelect').value;data.user.name=data.user.role==='Promoteur'?'Paul Mbarga':data.user.role==='Directeur'?'Diane Ndzié':'Sarah Etoundi';save();document.querySelector('#loginView').classList.add('hidden');document.querySelector('#appView').classList.remove('hidden');renderAll()});
document.querySelector('#logout').onclick=()=>{document.querySelector('#appView').classList.add('hidden');document.querySelector('#loginView').classList.remove('hidden')};
document.querySelector('#nav').onclick=e=>{const b=e.target.closest('[data-page]');if(b)setPage(b.dataset.page)};document.addEventListener('click',e=>{const go=e.target.closest('[data-go]');if(go)setPage(go.dataset.go);const create=e.target.closest('.create');if(create)openModal(create.dataset.type);if(e.target.closest('#quickAdd'))openModal('income');if(e.target.closest('.close'))document.querySelector('#modal').classList.add('hidden');const valid=e.target.closest('[data-validate]');if(valid){const x=data.expenses.find(y=>y.id===valid.dataset.validate);x.status='payée';x.validator=data.user.name;addAudit(`${data.user.name} a validé la dépense « ${x.label} »`);renderAll();toast('Dépense validée et comptabilisée.')}const pay=e.target.closest('[data-pay]');if(pay){const x=data.planned.find(y=>y.id===pay.dataset.pay);x.status='payée';data.expenses.unshift({id:'SOR-'+Date.now().toString().slice(-6),label:x.label,category:x.category,date:'2026-09-01',amount:x.amount,status:'payée',validator:data.user.name});addAudit(`${data.user.name} a enregistré le paiement « ${x.label} »`);save();renderAll();toast('Dépense marquée comme payée.')}const pt=e.target.closest('[data-payteacher]');if(pt){const x=data.teachers.find(y=>y.id===pt.dataset.payteacher);data.expenses.unshift({id:'SOR-'+Date.now().toString().slice(-6),label:`Rémunération — ${x.name}`,category:'Personnel',date:'2026-09-01',amount:x.due,status:'payée',validator:data.user.name});x.paid+=x.due;x.due=0;addAudit(`${data.user.name} a payé le formateur ${x.name}`);save();renderAll();toast('Paiement du formateur enregistré.')}});
document.querySelector('#operationForm').addEventListener('submit',submitOperation);document.querySelector('#incomeSearch').oninput=e=>filterTable('income',e.target.value);document.querySelector('#incomeFilter').onchange=e=>filterTable('income','',e.target.value);document.querySelector('#expenseSearch').oninput=e=>filterTable('expense',e.target.value);document.querySelector('#expenseStatus').onchange=e=>filterTable('expense','',e.target.value);function filterTable(type,q='',filter='all'){let arr=[...(type==='income'?data.incomes:data.expenses)];const input=document.querySelector(type==='income'?'#incomeSearch':'#expenseSearch');const sel=document.querySelector(type==='income'?'#incomeFilter':'#expenseStatus');q=q||input.value;filter=filter==='all'?sel.value:filter;arr=arr.filter(x=>(x.label+x.category).toLowerCase().includes(q.toLowerCase())&&(filter==='all'||(type==='income'?x.category:x.status)===filter));const old=type==='income'?data.incomes:data.expenses;if(type==='income')data.incomes=arr;else data.expenses=arr;renderTables();if(type==='income')data.incomes=old;else data.expenses=old}
document.querySelector('#printReport').onclick=()=>window.print();document.querySelector('#notificationBtn').onclick=()=>{setPage('planned');toast('Voici les échéances qui requièrent votre attention.');};
