/* Flux de trésorerie réel : calculé depuis les opérations enregistrées. */
const chartYear=document.querySelector('#chartYear');
const chartMonths=['Jan','Fév','Mars','Avr','Mai','Juin','Juil','Août','Sept','Oct','Nov','Déc'];
const chartDate=value=>new Date(`${value||''}T12:00:00`);
function availableChartYears(){const years=[...data.incomes||[],...data.expenses||[]].map(item=>chartDate(item.date).getFullYear()).filter(Number.isFinite);return [...new Set([new Date().getFullYear(),...years])].sort((a,b)=>b-a);}
function prepareChartYears(){const selected=Number(chartYear.value)||new Date().getFullYear();chartYear.innerHTML=availableChartYears().map(year=>`<option value="${year}" ${year===selected?'selected':''}>${year}</option>`).join('');}
function renderRealCashflow(){prepareChartYears();const year=Number(chartYear.value);const current=new Date();const endMonth=year===current.getFullYear()?current.getMonth():11;const startMonth=Math.max(0,endMonth-5);const months=Array.from({length:endMonth-startMonth+1},(_,index)=>startMonth+index);const incomes=(data.incomes||[]);const expenses=(data.expenses||[]).filter(item=>item.status==='payée'||item.status==='validée');const values=months.map(month=>{const sum=(items)=>items.filter(item=>{const date=chartDate(item.date);return date.getFullYear()===year&&date.getMonth()===month;}).reduce((total,item)=>total+Number(item.amount||0),0);return {month,income:sum(incomes),expense:sum(expenses)};});const maximum=Math.max(...values.flatMap(item=>[item.income,item.expense]),1);document.querySelector('#chartSubtitle').textContent=`Entrées et sorties de ${chartMonths[startMonth]} à ${chartMonths[endMonth]} ${year}`;document.querySelector('#chart').innerHTML=values.map(item=>`<div class="bar-set" data-month="${chartMonths[item.month]}"><i class="bar in" title="Entrées : ${money(item.income)}" style="height:${Math.max(item.income/maximum*100,0)}%"></i><i class="bar out" title="Sorties : ${money(item.expense)}" style="height:${Math.max(item.expense/maximum*100,0)}%"></i></div>`).join('');}
const previousRenderDashboard=renderDashboard;renderDashboard=function(due){previousRenderDashboard(due);renderRealCashflow();};
chartYear.addEventListener('change',renderRealCashflow);
