/* Prévisions distinctes des opérations réelles : lecture pour tous, édition pour Promoteur/Directeur. */
const forecastButton=document.querySelector('#addForecast');
const forecastModal=document.querySelector('#forecastModal');
let forecasts=[];let forecastsLoaded=false;
const canEditForecasts=()=>data.user&&['Promoteur','Directeur'].includes(data.user.role);
const forecastMonth=value=>new Date(`${value}-01T12:00:00`);
const forecastKey=date=>date.toISOString().slice(0,7);
const forecastMonthLabel=value=>new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(forecastMonth(value));
const realBalance=()=>((data.incomes||[]).reduce((sum,item)=>sum+Number(item.amount||0),0))-((data.expenses||[]).filter(item=>item.status==='payée'||item.status==='validée').reduce((sum,item)=>sum+Number(item.amount||0),0));
function projectionMonths(){const base=new Date();base.setDate(1);return Array.from({length:6},(_,index)=>{const date=new Date(base);date.setMonth(date.getMonth()+index);return forecastKey(date);});}
function sumForecast(month,kind){return forecasts.filter(item=>item.month===month&&item.kind===kind).reduce((sum,item)=>sum+Number(item.amount||0),0);}
function sumPlanned(month){return (data.planned||[]).filter(item=>item.status!=='payée'&&String(item.due||'').slice(0,7)===month).reduce((sum,item)=>sum+Number(item.amount||0),0);}
function sumActual(month,type){const items=type==='income'?(data.incomes||[]):(data.expenses||[]).filter(item=>item.status==='payée'||item.status==='validée');return items.filter(item=>String(item.date||'').slice(0,7)===month).reduce((sum,item)=>sum+Number(item.amount||0),0);}
function renderForecasts(){const months=projectionMonths();let balance=realBalance();const rows=months.map(month=>{const expectedIn=sumForecast(month,'income');const expectedOut=sumForecast(month,'expense')+sumPlanned(month);const actualIn=sumActual(month,'income');const actualOut=sumActual(month,'expense');balance+=expectedIn-expectedOut;return{month,expectedIn,expectedOut,actualIn,actualOut,balance};});const alerts=rows.filter(row=>row.balance<0).map(row=>`Risque de trésorerie insuffisante en ${forecastMonthLabel(row.month)}.`);rows.filter(row=>row.expectedOut>row.expectedIn&&row.balance>=0).forEach(row=>alerts.push(`Les charges prévues dépassent les entrées attendues en ${forecastMonthLabel(row.month)}.`));document.querySelector('#forecastCurrentBalance').textContent=money(realBalance());document.querySelector('#forecastEndBalance').textContent=money(rows.at(-1).balance);document.querySelector('#forecastAlertCount').textContent=alerts.length;document.querySelector('#forecastAlerts').innerHTML=alerts.map(alert=>`<div class="forecast-alert">⚠ ${escape(alert)}</div>`).join('')||'<div class="forecast-ok">✓ Aucune alerte de trésorerie sur les six prochains mois.</div>';document.querySelector('#forecastTable').innerHTML=rows.map(row=>`<tr><td><strong>${forecastMonthLabel(row.month)}</strong></td><td class="amount-income">${money(row.expectedIn)}</td><td class="amount-expense">${money(row.expectedOut)}</td><td>${money(row.actualIn)} / ${money(row.actualOut)}</td><td class="${row.balance<0?'amount-expense':'amount-income'}">${money(row.balance)}</td></tr>`).join('');}
async function loadForecasts(){if(forecastsLoaded||!accessToken)return;try{const result=await api('/api/forecasts');forecasts=result.forecasts||[];forecastsLoaded=true;renderForecasts();}catch(error){toast(error.message);}}
async function saveForecasts(){const result=await api('/api/forecasts',{method:'PUT',body:JSON.stringify({forecasts})});forecasts=result.forecasts||[];renderForecasts();}
forecastButton.addEventListener('click',()=>{document.querySelector('#forecastForm').reset();document.querySelector('#forecastForm [name="month"]').value=new Date().toISOString().slice(0,7);forecastModal.classList.remove('hidden');});
document.querySelector('#forecastForm').addEventListener('submit',async event=>{event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));forecasts.push({id:`PRV-${Date.now()}`,label:form.label,kind:form.kind,month:form.month,category:form.category,note:form.note,amount:Number(form.amount)});try{await saveForecasts();forecastModal.classList.add('hidden');toast('Prévision ajoutée.');}catch(error){toast(error.message);}});
document.addEventListener('click',event=>{if(event.target.closest('[data-close-forecast]'))forecastModal.classList.add('hidden');});
const forecastRenderAll=renderAll;renderAll=function(){forecastRenderAll();forecastButton.classList.toggle('hidden',!canEditForecasts());renderForecasts();loadForecasts();};
