/* Espace confidentiel de suivi du personnel permanent, sans effet sur la caisse. */
const permanentNav=document.querySelector('#permanentStaffNav');
const permanentModal=document.querySelector('#staffModal');
const permanentMonth=document.querySelector('#staffMonth');
let permanentStaff=[];
let staffLoaded=false;
const canManagePermanent=()=>data.user&&['Promoteur','Directeur'].includes(data.user.role);
const currentStaffMonth=()=>new Date().toISOString().slice(0,7);
const monthName=month=>new Intl.DateTimeFormat('fr-FR',{month:'long',year:'numeric'}).format(new Date(`${month}-01T12:00:00`));
function monthChoices(){const current=currentStaffMonth();const selected=permanentMonth.value||current;const months=[];for(let offset=-6;offset<=6;offset++){const date=new Date(`${current}-01T12:00:00`);date.setMonth(date.getMonth()+offset);months.push(date.toISOString().slice(0,7));}permanentMonth.innerHTML=months.map(month=>`<option value="${month}" ${month===selected?'selected':''}>${monthName(month)}</option>`).join('');}
const staffExtra=(staff,month)=>((staff.bonuses||[]).filter(item=>item.month===month).reduce((total,item)=>total+Number(item.amount||0),0));
const staffTotal=(staff,month)=>Number(staff.salary||0)+staffExtra(staff,month);
const staffPayment=(staff,month)=>(staff.payments||{})[month]||null;
function renderPermanentStaff(){if(!canManagePermanent())return;monthChoices();const month=permanentMonth.value;const payroll=permanentStaff.reduce((sum,staff)=>sum+Number(staff.salary||0),0);const bonuses=permanentStaff.reduce((sum,staff)=>sum+staffExtra(staff,month),0);const pending=permanentStaff.filter(staff=>!staffPayment(staff,month)).reduce((sum,staff)=>sum+staffTotal(staff,month),0);document.querySelector('#staffPayroll').textContent=money(payroll);document.querySelector('#staffBonuses').textContent=money(bonuses);document.querySelector('#staffPending').textContent=money(pending);document.querySelector('#permanentStaffTable').innerHTML=permanentStaff.map(staff=>{const paid=staffPayment(staff,month);const total=staffTotal(staff,month);return `<tr><td><strong>${escape(staff.name)}</strong></td><td>${escape(staff.position)}</td><td>${money(staff.salary)}</td><td>${money(staffExtra(staff,month))}</td><td><strong>${money(total)}</strong></td><td><span class="status ${paid?'payée':'prévue'}">${paid?'Payé':'À suivre'}</span></td><td class="right"><button class="action-mini" data-staff-bonus="${staff.id}">Prime</button> ${paid?`<button class="action-mini" data-staff-unpay="${staff.id}">Annuler paiement</button>`:`<button class="action-mini" data-staff-pay="${staff.id}">Marquer payé</button>`}</td></tr>`;}).join('')||'<tr><td colspan="7" class="muted">Aucun collaborateur permanent enregistré.</td></tr>';}
async function savePermanentStaff(){const result=await api('/api/permanent-staff',{method:'PUT',body:JSON.stringify({staff:permanentStaff})});permanentStaff=result.staff||[];renderPermanentStaff();}
async function loadPermanentStaff(){if(!canManagePermanent()||staffLoaded)return;try{const result=await api('/api/permanent-staff');permanentStaff=result.staff||[];staffLoaded=true;renderPermanentStaff();}catch(error){toast(error.message);}}
function showStaffModal(title,fields,onSubmit){document.querySelector('#staffModalTitle').textContent=title;document.querySelector('#staffFields').innerHTML=fields;document.querySelector('#staffForm').onsubmit=onSubmit;permanentModal.classList.remove('hidden');}
document.querySelector('#addPermanentStaff').addEventListener('click',()=>showStaffModal('Ajouter un collaborateur',`<div class="form-grid"><label class="wide">Nom complet<input name="name" required /></label><label>Poste<select name="position"><option>Promoteur</option><option>Directeur</option><option>Responsable scolarité</option><option>Assistante de scolarité</option></select></label><label>Salaire mensuel (FCFA)<input name="salary" type="number" min="0" required /></label></div>`,async event=>{event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));permanentStaff.push({id:`PER-${Date.now()}`,name:form.name,position:form.position,salary:Number(form.salary),bonuses:[],payments:{}});try{await savePermanentStaff();permanentModal.classList.add('hidden');toast('Collaborateur ajouté au suivi.');}catch(error){toast(error.message);}}));
document.addEventListener('click',event=>{if(event.target.closest('[data-close-staff]'))permanentModal.classList.add('hidden');const button=event.target.closest('[data-staff-pay],[data-staff-unpay],[data-staff-bonus]');if(!button)return;const staff=permanentStaff.find(item=>item.id===(button.dataset.staffPay||button.dataset.staffUnpay||button.dataset.staffBonus));if(!staff)return;const month=permanentMonth.value;if(button.dataset.staffPay){staff.payments=staff.payments||{};staff.payments[month]={paidAt:new Date().toISOString(),paidBy:data.user.name};savePermanentStaff().then(()=>toast('Paiement marqué comme effectué.')).catch(error=>toast(error.message));}if(button.dataset.staffUnpay){delete staff.payments[month];savePermanentStaff().then(()=>toast('Paiement remis à suivre.')).catch(error=>toast(error.message));}if(button.dataset.staffBonus){showStaffModal(`Prime ou bonus — ${staff.name}`,`<div class="form-grid"><label class="wide">Libellé<input name="label" required placeholder="Ex. Prime de rendement" /></label><label class="wide">Montant (FCFA)<input name="amount" type="number" min="1" required /></label></div>`,async submit=>{submit.preventDefault();const form=Object.fromEntries(new FormData(submit.currentTarget));staff.bonuses=staff.bonuses||[];staff.bonuses.push({id:`BON-${Date.now()}`,month,label:form.label,amount:Number(form.amount)});try{await savePermanentStaff();permanentModal.classList.add('hidden');toast('Prime ajoutée au mois sélectionné.');}catch(error){toast(error.message);}});}});
permanentMonth.addEventListener('change',renderPermanentStaff);
const permanentRenderAll=renderAll;renderAll=function(){permanentRenderAll();const permitted=canManagePermanent();permanentNav.classList.toggle('hidden',!permitted);if(permitted){renderPermanentStaff();loadPermanentStaff();}};
