/* Circuit séparé des demandes de dépenses à valider. */
const requestForm=document.querySelector('#operationForm');
const requestsNav=document.querySelector('#requestsNav');
const requestsPage=document.querySelector('#requests');
const isPromoter=()=>data.user&&data.user.role==='Promoteur';
const renderRequests=()=>{const items=data.requests||[];document.querySelector('#requestsBadge').textContent=items.filter(item=>item.status==='à valider').length;document.querySelector('#requestsTable').innerHTML=items.map(item=>`<tr><td>${escape(item.label)}</td><td>${escape(item.category)}</td><td>${escape(item.requester)}</td><td>${date(item.date)}</td><td><span class="status ${item.status==='approuvée'?'validée':item.status==='refusée'?'rejetée':'prévue'}">${escape(item.status)}</span></td><td class="right">${money(item.amount)}</td><td>${item.status==='à valider'&&isPromoter()?`<button class="action-mini" data-approve-request="${escape(item.id)}">Approuver</button> <button class="action-mini" data-reject-request="${escape(item.id)}">Refuser</button>`:''}</td></tr>`).join('')||'<tr><td colspan="7" class="muted">Aucune demande de dépense.</td></tr>';};
const showRequests=()=>{document.querySelectorAll('.page').forEach(page=>page.classList.toggle('active',page===requestsPage));document.querySelectorAll('.nav-link').forEach(button=>button.classList.remove('active'));requestsNav.classList.add('active');document.querySelector('#pageKicker').textContent='VALIDATION';document.querySelector('#pageTitle').textContent='Demandes de dépenses';renderRequests();};
const previousRenderAll=renderAll;renderAll=function(){if(!Array.isArray(data.requests))data.requests=[];previousRenderAll();renderRequests();};
requestsNav.addEventListener('click',event=>{event.preventDefault();event.stopImmediatePropagation();showRequests();},true);
document.querySelector('#createRequest').addEventListener('click',()=>{requestForm.dataset.request='true';currentType='request';document.querySelector('#modalTitle').textContent='Nouvelle demande de dépense';document.querySelector('#formFields').innerHTML=`<div class="form-grid"><label class="wide">Objet de la demande<input name="label" required placeholder="Ex. Achat d’un vidéoprojecteur" /></label><label>Montant (FCFA)<input name="amount" type="number" min="1" required /></label><label>Catégorie<select name="category"><option>Fournitures</option><option>Matériel</option><option>Maintenance</option><option>Personnel</option><option>Autre</option></select></label><label class="wide">Justification<input name="note" required placeholder="Motif de la demande" /></label></div>`;document.querySelector('#modal').classList.remove('hidden');});
requestForm.addEventListener('submit',event=>{if(!requestForm.dataset.request)return;event.preventDefault();event.stopImmediatePropagation();const values=Object.fromEntries(new FormData(requestForm));data.requests.unshift({id:'DEM-'+Date.now().toString().slice(-6),label:values.label,category:values.category,note:values.note,amount:Number(values.amount),date:new Date().toISOString().slice(0,10),requester:data.user.name,status:'à valider'});addAudit(`${data.user.name} a créé une demande de dépense « ${values.label} »`);delete requestForm.dataset.request;requestForm.onsubmit=null;document.querySelector('#modal').classList.add('hidden');renderAll();syncNow();toast('Demande envoyée pour validation.');},true);
document.addEventListener('click',event=>{const approve=event.target.closest('[data-approve-request]');const reject=event.target.closest('[data-reject-request]');if(!approve&&!reject)return;const request=(data.requests||[]).find(item=>item.id===(approve||reject).dataset[approve?'approveRequest':'rejectRequest']);if(!request||!isPromoter())return;if(approve){request.status='approuvée';data.expenses.unshift({id:'SOR-'+Date.now().toString().slice(-6),label:request.label,category:request.category,date:new Date().toISOString().slice(0,10),amount:request.amount,status:'payée',validator:data.user.name});addAudit(`${data.user.name} a approuvé la demande « ${request.label} »`);toast('Demande approuvée et sortie enregistrée.');}else{request.status='refusée';addAudit(`${data.user.name} a refusé la demande « ${request.label} »`);toast('Demande refusée.');}save();renderAll();syncNow();});
