/* Module Scolarité : spécialités, apprenants, échéanciers et recouvrement. */
(() => {
  const modal=document.querySelector('#schoolingModal');
  const content=document.querySelector('#schoolingContent');
  let schoolTab='overview';
  const DAY=86400000;
  const uniformPrices={polo:5000,maillot:5000,jogging:20000,pack:25000};
  const school=()=>{
    data.schooling=data.schooling&&typeof data.schooling==='object'?data.schooling:{specialties:[],learners:[],payments:[]};
    data.schooling.specialties=Array.isArray(data.schooling.specialties)?data.schooling.specialties:[];
    data.schooling.learners=Array.isArray(data.schooling.learners)?data.schooling.learners:[];
    data.schooling.payments=Array.isArray(data.schooling.payments)?data.schooling.payments:[];
    return data.schooling;
  };
  const now=()=>new Date();
  const isoToday=()=>now().toISOString().slice(0,10);
  const shortDate=value=>new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short',year:'numeric'}).format(new Date(`${value}T12:00:00`));
  const safe=v=>escape(v||'');
  const specialties=()=>school().specialties;
  const learners=()=>school().learners;
  const payments=()=>school().payments;
  const specialty=id=>specialties().find(item=>item.id===id);
  const learner=id=>learners().find(item=>item.id===id);
  const learnerPayments=(id,kind)=>payments().filter(item=>item.learnerId===id&&(!kind||item.kind===kind));
  const paid=(id,kind)=>learnerPayments(id,kind).reduce((total,item)=>total+Number(item.amount||0),0);
  const uniformRequired=person=>person.uniform==='pack'?uniformPrices.pack:Number(uniformPrices[person.uniform]||0);
  const daysUntil=value=>Math.ceil((new Date(`${value}T12:00:00`)-now())/DAY);
  const dueDate=person=>{const start=new Date(`${person.enrollmentDate}T12:00:00`);const periods=Math.floor((now()-start)/(30*DAY))+1;start.setDate(start.getDate()+periods*30);return start.toISOString().slice(0,10);};
  const firstPeriodPaid=person=>learnerPayments(person.id,'tuition').filter(item=>new Date(`${item.date}T12:00:00`)<=new Date(`${person.enrollmentDate}T12:00:00`).getTime()+30*DAY).reduce((sum,item)=>sum+Number(item.amount||0),0);
  function paymentRule(person){
    const program=specialty(person.specialtyId)||{};
    const initial=Number(program.initialMinimum||100000);
    const monthly=Number(program.monthlyMinimum||50000);
    const start=new Date(`${person.enrollmentDate}T12:00:00`);
    const elapsed=Math.max(0,Math.floor((now()-start)/(30*DAY)));
    const first=firstPeriodPaid(person);
    const required=elapsed>0&&first<initial?initial:elapsed>0?monthly:initial;
    return {initial,monthly,elapsed,first,required,nextDue:dueDate(person),critical:elapsed>0&&first<initial};
  }
  function paymentLabel(kind){return ({tuition:'Scolarité',exam:'Frais d’examen',defense:'Frais de soutenance',uniform:'Tenue CESAME'})[kind]||kind;}
  function saveSchooling(message){save();if(typeof syncNow==='function')syncNow();renderSchooling();if(message)toast(message);}
  function addAuditSchool(text){if(typeof addAudit==='function')addAudit(text);}
  function showModal(title,fields,submit){document.querySelector('#schoolingModalTitle').textContent=title;document.querySelector('#schoolingFields').innerHTML=fields;const form=document.querySelector('#schoolingForm');form.onsubmit=submit;modal.classList.remove('hidden');}
  function closeModal(){modal.classList.add('hidden');}
  function specialtyOptions(selected=''){return `<option value="">Choisir une spécialité</option>${specialties().map(item=>`<option value="${item.id}" ${item.id===selected?'selected':''}>${safe(item.name)} · ${item.durationMonths} mois</option>`).join('')}`;}
  function learnerStatus(person){const rule=paymentRule(person);const rest=Math.max(0,rule.required-paid(person.id,'tuition'));if(rule.critical)return {label:'Prioritaire',className:'rejetée',rest,rule};if(rest>0)return {label:'À relancer',className:'à valider',rest,rule};return {label:'À jour',className:'payée',rest:0,rule};}
  function notices(){return learners().map(person=>{const status=learnerStatus(person);const deadline=status.rule.nextDue;return {...person,status,deadline,days:daysUntil(deadline)};}).filter(item=>item.status.rest>0&&item.days<=5);}
  function summary(){const tuitionExpected=learners().reduce((total,person)=>total+paymentRule(person).required,0);const tuitionPaid=payments().filter(item=>item.kind==='tuition').reduce((total,item)=>total+Number(item.amount||0),0);const outstanding=Math.max(0,tuitionExpected-tuitionPaid);const critical=learners().filter(person=>learnerStatus(person).className==='rejetée').length;return {tuitionExpected,tuitionPaid,outstanding,critical,rate:tuitionExpected?Math.round(tuitionPaid/tuitionExpected*100):0};}
  function renderSchooling(){if(!content)return;const totals=summary();document.querySelectorAll('[data-school-tab]').forEach(button=>button.classList.toggle('active',button.dataset.schoolTab===schoolTab));if(schoolTab==='overview')content.innerHTML=overview(totals);if(schoolTab==='learners')content.innerHTML=learnerList();if(schoolTab==='specialties')content.innerHTML=specialtyList();if(schoolTab==='uniforms')content.innerHTML=uniformList();if(schoolTab==='reports')content.innerHTML=reportList(totals);}
  function overview(t){const alerts=notices();return `<div class="school-summary"><article><span>Apprenants actifs</span><strong>${learners().length}</strong></article><article><span>Recouvrement à date</span><strong>${t.rate}%</strong><small>${money(t.tuitionPaid)} encaissés</small></article><article><span>Reste à recouvrer</span><strong>${money(t.outstanding)}</strong></article><article><span>Cas prioritaires</span><strong>${t.critical}</strong></article></div><div class="school-grid"><article class="panel"><div class="panel-head"><div><h3>Échéances et relances</h3><p>Avis générés cinq jours avant l’échéance de 30 jours.</p></div><button class="text-btn" data-school-tab-go="learners">Voir les apprenants</button></div>${alerts.length?`<div class="school-alerts">${alerts.map(item=>`<div class="school-alert"><div><strong>${safe(item.name)}</strong><small>${safe(specialty(item.specialtyId)?.name||'Spécialité')} · échéance ${shortDate(item.deadline)}</small></div><span>${money(item.status.rest)}</span><button class="action-mini" data-school-notice="${item.id}">Avis</button></div>`).join('')}</div>`:'<p class="muted">Aucune relance à générer actuellement.</p>'}</article><article class="panel"><h3>Règle de paiement</h3><div class="school-rule"><strong>1re période : au moins 100 000 FCFA</strong><span>Ensuite : au moins 50 000 FCFA tous les 30 jours.</span><span>Si la première période n’est pas soldée, le minimum demandé le mois suivant reste 100 000 FCFA.</span></div><h3 class="school-subtitle">Derniers paiements</h3>${payments().slice().sort((a,b)=>b.date.localeCompare(a.date)).slice(0,4).map(item=>`<div class="compact-item"><div><strong>${safe(learner(item.learnerId)?.name||'Apprenant')}</strong><small>${paymentLabel(item.kind)} · ${shortDate(item.date)}</small></div><span class="amount">${money(item.amount)}</span></div>`).join('')||'<p class="muted">Aucun paiement enregistré.</p>'}</article></div>`;}
  function learnerList(){return `<div class="panel table-panel"><div class="filters"><input id="learnerSearch" placeholder="Rechercher un apprenant…" /><select id="learnerStatusFilter"><option value="all">Tous les états</option><option value="payée">À jour</option><option value="à valider">À relancer</option><option value="rejetée">Prioritaires</option></select></div><div class="table-wrap"><table><thead><tr><th>APPRENANT</th><th>SPÉCIALITÉ</th><th>INSCRIPTION</th><th>PROCHAINE ÉCHÉANCE</th><th>ÉTAT</th><th class="right">À VERSER</th><th></th></tr></thead><tbody>${learners().map(person=>{const status=learnerStatus(person);return `<tr data-learner-row="${person.id}"><td><strong>${safe(person.name)}</strong><small>${safe(person.phone||'—')}</small></td><td>${safe(specialty(person.specialtyId)?.name||'—')}</td><td>${shortDate(person.enrollmentDate)}</td><td>${shortDate(status.rule.nextDue)}</td><td><span class="status ${status.className}">${status.label}</span></td><td class="right">${money(status.rest)}</td><td class="right"><button class="action-mini" data-school-payment="${person.id}">Paiement</button> <button class="action-mini" data-school-profile="${person.id}">Fiche</button></td></tr>`;}).join('')||'<tr><td colspan="7" class="muted">Aucun apprenant enregistré.</td></tr>'}</tbody></table></div></div>`;}
  function specialtyList(){return `<div class="school-specialty-grid">${specialties().map(item=>`<article class="panel specialty-card"><span class="category">${item.durationMonths} MOIS</span><h3>${safe(item.name)}</h3><p>Frais scolarité de référence : <strong>${money(item.schoolFee||125000)}</strong><br>1re période : <strong>${money(item.initialMinimum)}</strong><br>Minimum mensuel : <strong>${money(item.monthlyMinimum)}</strong></p><div class="specialty-fees"><span>Examen <b>${money(item.examFee)}</b></span><span>Soutenance <b>${money(item.defenseFee)}</b></span></div><footer><span>${learners().filter(person=>person.specialtyId===item.id).length} apprenant(s)</span><button class="action-mini" data-school-edit-specialty="${item.id}">Modifier</button></footer></article>`).join('')||'<article class="panel"><p class="muted">Commencez par créer les spécialités du centre.</p></article>'}</div>`;}
  function uniformList(){return `<div class="panel"><div class="panel-head"><div><h3>Tenues CESAME</h3><p>Polo : 5 000 · Maillot : 5 000 · Jogging : 20 000 · Ensemble : 25 000 FCFA.</p></div></div><div class="table-wrap"><table><thead><tr><th>APPRENANT</th><th>TENUE CHOISIE</th><th>COÛT</th><th>PAYÉ</th><th>LIVRAISON</th><th></th></tr></thead><tbody>${learners().map(person=>{const expected=uniformRequired(person),received=paid(person.id,'uniform');return `<tr><td><strong>${safe(person.name)}</strong></td><td>${({polo:'Polo',maillot:'Maillot',jogging:'Jogging',pack:'Polo + maillot + jogging'})[person.uniform]||'Non définie'}</td><td>${money(expected)}</td><td>${money(received)}</td><td><span class="status ${person.uniformDelivered?'payée':'prévue'}">${person.uniformDelivered?'Remise':'À remettre'}</span></td><td class="right">${expected>received?`<button class="action-mini" data-school-payment="${person.id}" data-payment-kind="uniform">Encaisser</button> `:''}${expected&& !person.uniformDelivered?`<button class="action-mini" data-school-uniform-delivered="${person.id}">Remettre</button>`:''}</td></tr>`;}).join('')||'<tr><td colspan="6" class="muted">Aucun apprenant enregistré.</td></tr>'}</tbody></table></div></div>`;}
  function reportList(t){const atRisk=learners().filter(person=>learnerStatus(person).rest>0).sort((a,b)=>learnerStatus(b).rest-learnerStatus(a).rest);return `<div class="school-summary"><article><span>Taux de recouvrement</span><strong>${t.rate}%</strong></article><article><span>Encaissements scolarité</span><strong>${money(t.tuitionPaid)}</strong></article><article><span>Attendus à date</span><strong>${money(t.tuitionExpected)}</strong></article><article><span>Taux d’insolvabilité</span><strong>${learners().length?Math.round(atRisk.length/learners().length*100):0}%</strong></article></div><article class="panel"><h3>Cas à suivre en priorité</h3><div class="table-wrap"><table><thead><tr><th>APPRENANT</th><th>SPÉCIALITÉ</th><th>DERNIER VERSEMENT</th><th class="right">MONTANT À RÉGULARISER</th><th>ÉTAT</th></tr></thead><tbody>${atRisk.map(person=>{const p=learnerPayments(person.id).slice().sort((a,b)=>b.date.localeCompare(a.date))[0];const status=learnerStatus(person);return `<tr><td><strong>${safe(person.name)}</strong></td><td>${safe(specialty(person.specialtyId)?.name||'—')}</td><td>${p?`${shortDate(p.date)} · ${money(p.amount)}`:'Aucun paiement'}</td><td class="right">${money(status.rest)}</td><td><span class="status ${status.className}">${status.label}</span></td></tr>`;}).join('')||'<tr><td colspan="5" class="muted">Aucun impayé à signaler.</td></tr>'}</tbody></table></div></article>`;}
  function showSpecialtyForm(item){item=item||{};showModal(item.id?'Modifier une spécialité':'Ajouter une spécialité',`<div class="form-grid"><label class="wide">Nom de la spécialité<input name="name" required value="${safe(item.name)}" placeholder="Ex. Maintenance informatique" /></label><label>Durée (mois)<input name="durationMonths" type="number" min="1" max="24" required value="${item.durationMonths||12}" /></label><label>Frais scolarité de référence<input name="schoolFee" type="number" min="0" required value="${item.schoolFee||125000}" /></label><label>1re période minimum<input name="initialMinimum" type="number" min="0" required value="${item.initialMinimum||100000}" /></label><label>Minimum tous les 30 jours<input name="monthlyMinimum" type="number" min="0" required value="${item.monthlyMinimum||50000}" /></label><label>Frais d’examen<input name="examFee" type="number" min="0" required value="${item.examFee||0}" /></label><label>Frais de soutenance<input name="defenseFee" type="number" min="0" required value="${item.defenseFee||25000}" /></label></div>`,event=>{event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));const target=item.id||`SPE-${Date.now()}`;const record={id:target,name:form.name.trim(),durationMonths:Number(form.durationMonths),schoolFee:Number(form.schoolFee),initialMinimum:Number(form.initialMinimum),monthlyMinimum:Number(form.monthlyMinimum),examFee:Number(form.examFee),defenseFee:Number(form.defenseFee)};const index=specialties().findIndex(entry=>entry.id===target);if(index>=0)specialties()[index]=record;else specialties().push(record);addAuditSchool(`${data.user.name} a ${index>=0?'modifié':'ajouté'} la spécialité « ${record.name} »`);closeModal();saveSchooling('Spécialité enregistrée.');});}
  function showLearnerForm(){if(!specialties().length){toast('Créez d’abord au moins une spécialité.');return;}showModal('Ajouter un apprenant',`<div class="form-grid"><label class="wide">Nom complet<input name="name" required placeholder="Nom et prénom de l’apprenant" /></label><label>Spécialité<select name="specialtyId" required>${specialtyOptions()}</select></label><label>Date d’entrée<input name="enrollmentDate" type="date" value="2026-09-28" required /></label><label>Téléphone / WhatsApp<input name="phone" placeholder="6XX XXX XXX" /></label><label>Tenue CESAME<select name="uniform"><option value="">Aucune à ce stade</option><option value="polo">Polo — 5 000 FCFA</option><option value="maillot">Maillot — 5 000 FCFA</option><option value="jogging">Jogging — 20 000 FCFA</option><option value="pack">Polo + maillot + jogging — 25 000 FCFA</option></select></label></div>`,event=>{event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));learners().push({id:`APP-${Date.now()}`,name:form.name.trim(),specialtyId:form.specialtyId,enrollmentDate:form.enrollmentDate,phone:form.phone.trim(),uniform:form.uniform,uniformDelivered:false});addAuditSchool(`${data.user.name} a inscrit l’apprenant ${form.name.trim()}`);closeModal();saveSchooling('Apprenant enregistré.');});}
  function showPaymentForm(person,forcedKind=''){const program=specialty(person.specialtyId)||{};const rule=paymentRule(person);const defaultKind=forcedKind||'tuition';const amount=defaultKind==='uniform'?Math.max(0,uniformRequired(person)-paid(person.id,'uniform')):defaultKind==='exam'?Number(program.examFee||0):defaultKind==='defense'?Number(program.defenseFee||25000):rule.required;showModal(`Encaisser — ${person.name}`,`<div class="form-grid"><label class="wide">Apprenant<input value="${safe(person.name)}" disabled /></label><label>Nature du paiement<select name="kind"><option value="tuition" ${defaultKind==='tuition'?'selected':''}>Scolarité</option><option value="uniform" ${defaultKind==='uniform'?'selected':''}>Tenue CESAME</option><option value="exam" ${defaultKind==='exam'?'selected':''}>Frais d’examen</option><option value="defense" ${defaultKind==='defense'?'selected':''}>Frais de soutenance</option></select></label><label>Montant (FCFA)<input name="amount" type="number" min="1" value="${amount}" required /></label><label>Date<input name="date" type="date" value="${isoToday()}" required /></label><label>Mode<select name="mode"><option>Espèces</option><option>MTN MoMo</option><option>Orange Money</option><option>Virement</option></select></label><label class="wide">Observation<input name="note" placeholder="N° reçu ou précision" /></label></div><p class="form-hint">Minimum attendu sur la période : ${money(rule.required)}. Total scolarité déjà reçu : ${money(paid(person.id,'tuition'))}.</p>`,event=>{event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));const entry={id:`PAY-${Date.now()}`,learnerId:person.id,kind:form.kind,amount:Number(form.amount),date:form.date,mode:form.mode,note:form.note||''};payments().push(entry);data.incomes.unshift({id:`ENT-${Date.now().toString().slice(-6)}`,label:`${paymentLabel(entry.kind)} — ${person.name}`,category:paymentLabel(entry.kind),date:entry.date,mode:entry.mode,amount:entry.amount});addAuditSchool(`${data.user.name} a enregistré ${money(entry.amount)} pour ${person.name}`);closeModal();saveSchooling('Paiement enregistré et ajouté aux entrées financières.');if(typeof renderAll==='function')renderAll();});}
  function showProfile(person){const program=specialty(person.specialtyId)||{};const status=learnerStatus(person);const history=learnerPayments(person.id).slice().sort((a,b)=>b.date.localeCompare(a.date));showModal(`Fiche — ${person.name}`,`<div class="school-profile"><p><strong>${safe(program.name||'Spécialité non définie')}</strong><br><span>Entrée : ${shortDate(person.enrollmentDate)} · ${safe(person.phone||'Sans téléphone')}</span></p><div class="school-summary compact"><article><span>Scolarité reçue</span><strong>${money(paid(person.id,'tuition'))}</strong></article><article><span>Minimum actuel</span><strong>${money(status.rule.required)}</strong></article><article><span>État</span><strong>${status.label}</strong></article></div><h3>Historique des paiements</h3>${history.map(item=>`<div class="compact-item"><div><strong>${paymentLabel(item.kind)}</strong><small>${shortDate(item.date)} · ${safe(item.mode)}</small></div><span>${money(item.amount)}</span></div>`).join('')||'<p class="muted">Aucun paiement enregistré.</p>'}</div>`,event=>{event.preventDefault();closeModal();});}
  function showNotice(person){const status=learnerStatus(person);const program=specialty(person.specialtyId)||{};const message=`CESAME — AVIS DE RÈGLEMENT\n\nApprenant : ${person.name}\nSpécialité : ${program.name||'—'}\nDate d’entrée : ${shortDate(person.enrollmentDate)}\nProchaine échéance : ${shortDate(status.rule.nextDue)}\nMontant minimum à régulariser : ${money(status.rest)}\n\nMerci de vous rapprocher de la scolarité avant l’échéance.`;const popup=window.open('','_blank','width=650,height=700');if(!popup){toast('Autorisez les fenêtres contextuelles pour imprimer l’avis.');return;}popup.document.write(`<pre style="font:16px/1.6 Arial;padding:40px;white-space:pre-wrap">${safe(message)}</pre><script>window.print()<\/script>`);popup.document.close();}
  document.querySelector('#addSpecialty').addEventListener('click',()=>showSpecialtyForm());
  document.querySelector('#addLearner').addEventListener('click',showLearnerForm);
  document.addEventListener('click',event=>{if(event.target.closest('[data-close-schooling]'))closeModal();const tab=event.target.closest('[data-school-tab],[data-school-tab-go]');if(tab){schoolTab=tab.dataset.schoolTab||tab.dataset.schoolTabGo;renderSchooling();return;}const edit=event.target.closest('[data-school-edit-specialty]');if(edit)showSpecialtyForm(specialty(edit.dataset.schoolEditSpecialty));const pay=event.target.closest('[data-school-payment]');if(pay)showPaymentForm(learner(pay.dataset.schoolPayment),pay.dataset.paymentKind||'');const profile=event.target.closest('[data-school-profile]');if(profile)showProfile(learner(profile.dataset.schoolProfile));const notice=event.target.closest('[data-school-notice]');if(notice)showNotice(learner(notice.dataset.schoolNotice));const delivered=event.target.closest('[data-school-uniform-delivered]');if(delivered){const person=learner(delivered.dataset.schoolUniformDelivered);person.uniformDelivered=true;addAuditSchool(`${data.user.name} a marqué la tenue de ${person.name} comme remise`);saveSchooling('Tenue marquée comme remise.');}});
  document.addEventListener('input',event=>{if(event.target.id==='learnerSearch'){const query=event.target.value.toLowerCase();document.querySelectorAll('[data-learner-row]').forEach(row=>row.classList.toggle('hidden',!row.textContent.toLowerCase().includes(query)));}});
  document.addEventListener('change',event=>{if(event.target.id==='learnerStatusFilter'){const value=event.target.value;document.querySelectorAll('[data-learner-row]').forEach(row=>{const person=learner(row.dataset.learnerRow);row.classList.toggle('hidden',value!=='all'&&learnerStatus(person).className!==value);});}});
  const baseSetPage=setPage;setPage=function(page){baseSetPage(page);if(page==='schooling')renderSchooling();};
  const baseRenderAll=renderAll;renderAll=function(){baseRenderAll();if(document.querySelector('#schooling')?.classList.contains('active'))renderSchooling();};
  const baseTeacherFields=fields;fields=function(type){if(type!=='teacher')return baseTeacherFields(type);return `<div class="form-grid"><label class="wide">Nom complet<input name="name" required placeholder="Ex. Anne Ndzié" /></label><label>Spécialité<select name="specialtyId">${specialtyOptions()}</select></label><label>Module enseigné<input name="module" required placeholder="Ex. Création graphique" /></label><label>Nombre d’heures<input name="hours" type="number" min="1" required /></label><label>Rémunération prévue<input name="amount" type="number" min="0" required /></label></div>`;};
  document.querySelector('#operationForm').addEventListener('submit',event=>{if(currentType!=='teacher')return;event.preventDefault();event.stopImmediatePropagation();const form=Object.fromEntries(new FormData(event.currentTarget));const amount=Number(form.amount);data.teachers.unshift({id:`FOR-${Date.now()}`,name:form.name,course:form.module,due:amount,paid:0,initials:initials(form.name),specialtyId:form.specialtyId,modules:[{name:form.module,hours:Number(form.hours),amount}]});addAuditSchool(`${data.user.name} a affecté le module « ${form.module} » à ${form.name}`);save();document.querySelector('#modal').classList.add('hidden');renderAll();if(typeof syncNow==='function')syncNow();toast('Formateur et module enregistrés.');},true);
  const baseRenderTeachers=renderTeachers;renderTeachers=function(){baseRenderTeachers();document.querySelector('#teacherCards').innerHTML=data.teachers.map(teacher=>{const program=specialty(teacher.specialtyId);const modules=Array.isArray(teacher.modules)&&teacher.modules.length?teacher.modules:[{name:teacher.course||'Module à préciser',hours:0,amount:teacher.due||0}];return `<article class="teacher-card"><div class="teacher-head"><div class="avatar">${teacher.initials||initials(teacher.name)}</div><div><strong>${safe(teacher.name)}</strong><small>${safe(program?.name||'Spécialité non affectée')}</small></div></div><div class="teacher-modules">${modules.map(module=>`<span>${safe(module.name)} · ${module.hours||0} h</span>`).join('')}</div><div class="teacher-due">Montant à payer <strong>${money(teacher.due)}</strong></div><footer><span>Payé : ${money(teacher.paid)}</span><span><button class="action-mini" data-teacher-module="${teacher.id}">+ Module</button> ${teacher.due?`<button class="action-mini" data-payteacher="${teacher.id}">Payer</button>`:'<em>À jour</em>'}</span></footer></article>`;}).join('');};
  document.addEventListener('click',event=>{const button=event.target.closest('[data-teacher-module]');if(!button)return;const teacher=data.teachers.find(item=>item.id===button.dataset.teacherModule);if(!teacher)return;showModal(`Affecter un module — ${teacher.name}`,`<div class="form-grid"><label class="wide">Module<input name="module" required placeholder="Ex. Mise en page et impression" /></label><label>Nombre d’heures<input name="hours" type="number" min="1" required /></label><label>Rémunération prévue<input name="amount" type="number" min="0" required /></label></div>`,submit=>{submit.preventDefault();const form=Object.fromEntries(new FormData(submit.currentTarget));teacher.modules=Array.isArray(teacher.modules)?teacher.modules:[];teacher.modules.push({name:form.module,hours:Number(form.hours),amount:Number(form.amount)});teacher.course=teacher.modules.map(item=>item.name).join(', ');teacher.due=teacher.modules.reduce((total,item)=>total+Number(item.amount||0),0)-Number(teacher.paid||0);addAuditSchool(`${data.user.name} a affecté le module « ${form.module} » à ${teacher.name}`);closeModal();save();if(typeof syncNow==='function')syncNow();renderAll();toast('Module affecté au formateur.');});});
})();
