/* Planification indépendante des modules pédagogiques et affectation des formateurs. */
(() => {
  const moduleList=()=>{data.trainingModules=Array.isArray(data.trainingModules)?data.trainingModules:[];return data.trainingModules;};
  const schoolSpecialties=()=>Array.isArray(data.schooling?.specialties)?data.schooling.specialties:[];
  const program=id=>schoolSpecialties().find(item=>item.id===id);
  const monthStart=()=>new Date().toISOString().slice(0,7)+'-01';
  const monthEnd=()=>{const date=new Date(`${monthStart()}T12:00:00`);date.setMonth(date.getMonth()+1);date.setDate(0);return date.toISOString().slice(0,10);};
  const moduleModal=document.querySelector('#schoolingModal');
  const openModuleModal=(title,fields,handler)=>{document.querySelector('#schoolingModalTitle').textContent=title;document.querySelector('#schoolingFields').innerHTML=fields;document.querySelector('#schoolingForm').onsubmit=handler;moduleModal.classList.remove('hidden');};
  const closeModuleModal=()=>moduleModal.classList.add('hidden');
  const specialtyOptions=(selected='')=>`<option value="">Sans spécialité précise</option>${schoolSpecialties().map(item=>`<option value="${item.id}" ${item.id===selected?'selected':''}>${escape(item.name)}</option>`).join('')}`;
  const teacherOptions=(selected='')=>`<option value="">Non affecté pour l’instant</option>${data.teachers.map(item=>`<option value="${item.id}" ${item.id===selected?'selected':''}>${escape(item.name)}</option>`).join('')}`;
  function recalculateTeacher(teacher){const modules=moduleList().filter(item=>item.teacherId===teacher.id);teacher.modules=modules.map(item=>({id:item.id,name:item.name,hours:item.hours,amount:item.amount,periodStart:item.periodStart,periodEnd:item.periodEnd}));teacher.course=teacher.modules.map(item=>item.name).join(', ')||'Aucun module affecté';teacher.due=Math.max(0,teacher.modules.reduce((sum,item)=>sum+Number(item.amount||0),0)-Number(teacher.paid||0));}
  function renderModules(){const container=document.querySelector('#teachingModulesSummary');if(!container)return;const current=moduleList().filter(item=>item.periodStart<=monthEnd()&&item.periodEnd>=monthStart());const intervenants=new Set(current.filter(item=>item.teacherId).map(item=>item.teacherId)).size;container.innerHTML=`<article class="panel teaching-panel"><div class="panel-head"><div><h3>Programmation pédagogique</h3><p>${current.length} module(s) prévu(s) pour la période en cours · ${intervenants} formateur(s) affecté(s).</p></div><button class="text-btn" id="addTeachingModule">+ Ajouter un module</button></div>${current.length?`<div class="module-list">${current.map(item=>`<div class="module-row"><div><strong>${escape(item.name)}</strong><small>${escape(program(item.specialtyId)?.name||'Toutes spécialités')} · ${item.hours} h · du ${new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short'}).format(new Date(`${item.periodStart}T12:00:00`))} au ${new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'short'}).format(new Date(`${item.periodEnd}T12:00:00`))}</small></div><div><span>${item.teacherId?escape(data.teachers.find(teacher=>teacher.id===item.teacherId)?.name||'Formateur'):'Non affecté'}</span><strong>${money(item.amount)}</strong><button class="action-mini" data-edit-teaching-module="${item.id}">Modifier</button></div></div>`).join('')}</div>`:'<p class="muted">Aucun module programmé pour cette période. Ajoutez-les à l’avance, puis affectez les formateurs quand ils sont confirmés.</p>'}</article>`;}
  function moduleForm(item={}){openModuleModal(item.id?'Modifier un module':'Ajouter un module',`<div class="form-grid"><label class="wide">Intitulé du module<input name="name" required value="${escape(item.name||'')}" placeholder="Ex. Dessin technique" /></label><label>Spécialité<select name="specialtyId">${specialtyOptions(item.specialtyId)}</select></label><label>Formateur affecté<select name="teacherId">${teacherOptions(item.teacherId)}</select></label><label>Début de programmation<input name="periodStart" type="date" required value="${item.periodStart||monthStart()}" /></label><label>Fin de programmation<input name="periodEnd" type="date" required value="${item.periodEnd||monthEnd()}" /></label><label>Nombre d’heures<input name="hours" type="number" min="1" required value="${item.hours||''}" /></label><label>Rémunération prévue<input name="amount" type="number" min="0" required value="${item.amount||''}" /></label></div>`,event=>{event.preventDefault();const form=Object.fromEntries(new FormData(event.currentTarget));const previousTeacher=item.teacherId&&data.teachers.find(teacher=>teacher.id===item.teacherId);const record={id:item.id||`MOD-${Date.now()}`,name:form.name.trim(),specialtyId:form.specialtyId,teacherId:form.teacherId,periodStart:form.periodStart,periodEnd:form.periodEnd,hours:Number(form.hours),amount:Number(form.amount)};const index=moduleList().findIndex(entry=>entry.id===record.id);if(index>=0)moduleList()[index]=record;else moduleList().push(record);[previousTeacher,data.teachers.find(teacher=>teacher.id===record.teacherId)].filter(Boolean).forEach(recalculateTeacher);addAudit(`${data.user.name} a ${index>=0?'modifié':'programmé'} le module « ${record.name} »`);closeModuleModal();save();if(typeof syncNow==='function')syncNow();renderAll();toast('Module pédagogique enregistré.');});}
  document.querySelector('#manageTeachingModules').addEventListener('click',()=>{document.querySelector('#teachers').scrollIntoView({behavior:'smooth'});renderModules();});
  document.addEventListener('click',event=>{if(event.target.closest('#addTeachingModule'))moduleForm();const edit=event.target.closest('[data-edit-teaching-module]');if(edit){const item=moduleList().find(entry=>entry.id===edit.dataset.editTeachingModule);if(item)moduleForm(item);}});
  const teacherRenderer=renderTeachers;renderTeachers=function(){teacherRenderer();renderModules();};
})();
